### ISSUE TITLE
where is the train.py

### ISSUE THREAD

**Issue by Lvhhhh** [faustomilletari/CFCM-2D#1]
i dont find the train.py and how to use it without docker? can you offer more details how to run this code?

**Comment by faustomilletari** [comment]
Run `pip install -e .` in the directory where you have cloned the code. Then run python -m cfcm_train plus the required arguments. You find these arguments in the file cli.py in the directory cfcm. @marcoesposito1988 can you confirm? Could you also update the Readme accordingly?

**Comment by marcoesposito1988** [comment]
The `train.py` file got renamed to `cfcm/cli.py`, which exposes the `train` command. 

I will update the README, thanks for pinging us!
